services:
  nrizky:
    build: .
    container_name: nrizky
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nrizky.rule=Host(`nrizky.com`)"
      - "traefik.http.routers.nrizky.entrypoints=websecure"
      - "traefik.http.routers.nrizky.tls.certresolver=le"
      - "traefik.http.services.nrizky.loadbalancer.server.port=3000"

    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
